synopsis.pdf: synposis.md killya_relational_schema.png killya_er_model.png
	pandoc -o synopsis.pdf synopsis.md

synopsis.html: synposis.md killya_relational_schema.png killya_er_model.png
	markdown synopsis.md > synopsis.html

